Спринт 10!
dudyrevanatalie/java-filmorate pull request #4
Opened 2023-03-22 09:33 UTC by dudyrevanatalie

2023-03-22 18:54 UTC, z8q requested changes

2023-03-22 18:54 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film add(@RequestBody Film film) {
Допускается добавление фильма с одинаковыми полями.
Можно было бы проверять по equals 4 поля:
String name;
String description;
LocalDate releaseDate;
int duration;
Что если все 4 поля совпадают у 2-х объектов, то не добавлять второй

2023-03-22 18:54 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    String description;
Почему решили убрать private у полей?

2023-03-23 07:57 UTC, dudyrevanatalie commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
done

2023-03-23 09:25 UTC, dudyrevanatalie commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void addToFriends(@PathVariable long id, @PathVariable long friendId) {
Done

2023-03-23 09:57 UTC, dudyrevanatalie commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film add(@RequestBody Film film) {
done

2023-03-23 10:06 UTC, dudyrevanatalie commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    UserStorage userStorage;
done

2023-03-23 10:06 UTC, dudyrevanatalie commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    long id = 1;
done

2023-03-23 19:04 UTC, z8q approved these changes

2023-03-24 18:56 UTC, merged